"""Bake the original Krypton Egg (C2V, Windows CD release 1996) resources into Godot files.

Usage: python3 tools/bake_assets.py <dir written by tools/carve_cd.py>

This writes:
  assets/gfx/<bank>.png     one sprite sheet per GAF sprite bank
  assets/gfx/pic_<name>.png the full-screen GIF pictures
  assets/sfx/<name>.wav     every sample, widened to 16-bit PCM
  assets/levels/ke.lvl      the 100 levels, copied byte for byte
  assets/fli/<nn>.fli       the eight FLI cutscenes, copied byte for byte
  scripts/atlas_data.gd     sprite rectangles and draw offsets
"""

import shutil
import struct
import sys
import wave
from pathlib import Path

import dig
import gaf
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
GAME_BANKS = [
    "KE_BRICK",
    "KE_NMY",
    "KE_RACK",
    "KE_SPELL",
    "KE_FILL",
    "KE_BORD",
    "KE_MONST",
    "KE_LOGO",
]
OWN_PAL_BANKS = ["KE_DIGIT", "KE_FONT", "KE_MENU", "KE_INFOS"]
SHEET_W = 512


def pack(sprites, pal):
    """Shelf-pack sprites into one RGBA sheet; return image and [x, y, w, h, ox, oy] rows."""
    rows, x, y, shelf = [], 1, 1, 0
    for s in sprites:
        w, h = max(s["w"], 1), max(s["h"], 1)
        if x + w + 1 > SHEET_W:
            x, y, shelf = 1, y + shelf + 1, 0
        rows.append([x, y, w, h, s["x"], s["y"]])
        x += w + 1
        shelf = max(shelf, h)
    im = Image.new("RGBA", (SHEET_W, y + shelf + 1), (0, 0, 0, 0))
    for s, r in zip(sprites, rows):
        im.alpha_composite(gaf.to_image(s, pal), (r[0], r[1]))
    return im, rows


def bake_banks(src, gd_lines):
    _, _, game_pal, _ = gaf.load(src / "KE_BRICK.GAF")
    for name in GAME_BANKS + OWN_PAL_BANKS:
        _, _, pal, sprites = gaf.load(src / f"{name}.GAF")
        im, rows = pack(sprites, pal or game_pal)
        key = name[3:].lower()
        im.save(ROOT / "assets/gfx" / f"{key}.png")
        gd_lines.append(f'\t"{key}": {rows},')
        print(f"{key}: {len(rows)} sprites, sheet {im.size}")


def bake_pictures(src):
    for pic in sorted(src.glob("PIC_*.png")):
        shutil.copy(pic, ROOT / "assets/gfx" / f"pic_{pic.stem[4:].lower()}.png")


def bake_sounds(src):
    for bank in sorted(src.glob("*.GAF")):
        if "DIG_" not in gaf.chunks(bank.read_bytes()):
            continue
        for name, rate, _loop, pcm in dig.sounds(bank):
            wide = struct.pack(f"<{len(pcm)}h", *((b - 128) << 8 for b in pcm))
            with wave.open(str(ROOT / "assets/sfx" / f"{name.lower()}.wav"), "wb") as w:
                w.setnchannels(1)
                w.setsampwidth(2)
                w.setframerate(rate)
                w.writeframes(wide)


def main():
    src = Path(sys.argv[1])
    for sub in ("assets/gfx", "assets/sfx", "assets/levels", "assets/fli"):
        (ROOT / sub).mkdir(parents=True, exist_ok=True)
    gd = [
        "extends RefCounted",
        "## Generated by tools/bake_assets.py. Per bank: [x, y, w, h, draw_ox, draw_oy].",
        "",
        "const BANKS := {",
    ]
    bake_banks(src, gd)
    gd.append("}")
    (ROOT / "scripts/atlas_data.gd").write_text("\n".join(gd) + "\n")
    bake_pictures(src)
    bake_sounds(src)
    shutil.copy(src / "KE.LVL", ROOT / "assets/levels/ke.lvl.bin")
    for fli in sorted(src.glob("*.fli")):
        shutil.copy(fli, ROOT / "assets/fli" / f"{fli.stem}.fli.bin")


if __name__ == "__main__":
    main()
